spring:
  application:
    name: cloud-consumer-order80

server:
  port: 80

eureka:
  instance:
    instance-id: consumer-order80
    prefer-ip-address: true #访问路径可以显示IP
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver7001.com:7001/eureka,http://eurekaserver7002.com:7002/eureka