server:
  port: 80
spring:
  application:
    name: cloud-consumer-order

eureka:
  instance:
    instance-id: consumer-order80
    prefer-ip-address: true #访问路径可以显示IP
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver7001.com:7001/eureka,http://eurekaserver7002.com:7002/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    org.zerofwk.example.cloud.order.service.PaymentOpenfeignService: debug

