server:
  port: 9527

spring:
  application:
    name: cloud-gateway9527
  cloud:
    gateway:
      routes:
        - id: payment_route_01
          uri: lb://CLOUD-PROVIDER-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
            #- Cookie=username,lizhaning
            #- Header=X-Request-Id,\d+

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eurekaserver7001.com:7001/eureka