server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'