server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment-service

eureka:
  instance:
    instance-id: payment8001
    lease-renewal-interval-in-seconds: 1       # 向服务端发送心跳间隔，默认30秒
    lease-expiration-duration-in-seconds: 2    # 收到最后一次心跳后等待的间隔，默认90秒，超时将剔除
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver7001.com:7001/eureka
